//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCReadTable
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RfcReadTable.RfcException", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcReadTableRfcException
    {
        
        private RfcReadTableRfcExceptions nameField;
        
        private string textField;
        
        private RfcExceptionMessage messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RfcReadTableRfcExceptions Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RfcExceptionMessage Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RfcReadTable.RfcExceptions", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public enum RfcReadTableRfcExceptions
    {
        
        /// <remarks/>
        DataBufferExceeded,
        
        /// <remarks/>
        FieldNotValid,
        
        /// <remarks/>
        NotAuthorized,
        
        /// <remarks/>
        OptionNotValid,
        
        /// <remarks/>
        TableNotAvailable,
        
        /// <remarks/>
        TableWithoutData,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RfcException.Message", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcExceptionMessage
    {
        
        private string idField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcDbOpt
    {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcDbFld
    {
        
        private string fieldnameField;
        
        private string offsetField;
        
        private string lengthField;
        
        private string typeField;
        
        private string fieldtextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Fieldname
        {
            get
            {
                return this.fieldnameField;
            }
            set
            {
                this.fieldnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Offset
        {
            get
            {
                return this.offsetField;
            }
            set
            {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Fieldtext
        {
            get
            {
                return this.fieldtextField;
            }
            set
            {
                this.fieldtextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Tab512
    {
        
        private string waField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Wa
        {
            get
            {
                return this.waField;
            }
            set
            {
                this.waField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="RFCReadTable.ZWS_RFC_READ_TABLE")]
    public interface ZWS_RFC_READ_TABLE
    {
        
        // CODEGEN: Generating message contract since the operation RfcReadTable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_RFC_READ_TABLE:RfcReadTableR" +
            "equest", ReplyAction="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_RFC_READ_TABLE:RfcReadTableR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RFCReadTable.RfcReadTableRfcException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="RfcReadTable.Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RFCReadTable.RfcReadTableResponse1 RfcReadTable(RFCReadTable.RfcReadTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_RFC_READ_TABLE:RfcReadTableR" +
            "equest", ReplyAction="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_RFC_READ_TABLE:RfcReadTableR" +
            "esponse")]
        System.Threading.Tasks.Task<RFCReadTable.RfcReadTableResponse1> RfcReadTableAsync(RFCReadTable.RfcReadTableRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcReadTable
    {
        
        private Tab512[] dataField;
        
        private string delimiterField;
        
        private RfcDbFld[] fieldsField;
        
        private string noDataField;
        
        private RfcDbOpt[] optionsField;
        
        private string queryTableField;
        
        private int rowcountField;
        
        private bool rowcountFieldSpecified;
        
        private int rowskipsField;
        
        private bool rowskipsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Tab512[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Delimiter
        {
            get
            {
                return this.delimiterField;
            }
            set
            {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RfcDbFld[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NoData
        {
            get
            {
                return this.noDataField;
            }
            set
            {
                this.noDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RfcDbOpt[] Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string QueryTable
        {
            get
            {
                return this.queryTableField;
            }
            set
            {
                this.queryTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int Rowcount
        {
            get
            {
                return this.rowcountField;
            }
            set
            {
                this.rowcountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RowcountSpecified
        {
            get
            {
                return this.rowcountFieldSpecified;
            }
            set
            {
                this.rowcountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int Rowskips
        {
            get
            {
                return this.rowskipsField;
            }
            set
            {
                this.rowskipsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RowskipsSpecified
        {
            get
            {
                return this.rowskipsFieldSpecified;
            }
            set
            {
                this.rowskipsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcReadTableResponse
    {
        
        private Tab512[] dataField;
        
        private RfcDbFld[] fieldsField;
        
        private RfcDbOpt[] optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Tab512[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RfcDbFld[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RfcDbOpt[] Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RfcReadTableRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public RFCReadTable.RfcReadTable RfcReadTable;
        
        public RfcReadTableRequest()
        {
        }
        
        public RfcReadTableRequest(RFCReadTable.RfcReadTable RfcReadTable)
        {
            this.RfcReadTable = RfcReadTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RfcReadTableResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public RFCReadTable.RfcReadTableResponse RfcReadTableResponse;
        
        public RfcReadTableResponse1()
        {
        }
        
        public RfcReadTableResponse1(RFCReadTable.RfcReadTableResponse RfcReadTableResponse)
        {
            this.RfcReadTableResponse = RfcReadTableResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ZWS_RFC_READ_TABLEChannel : RFCReadTable.ZWS_RFC_READ_TABLE, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ZWS_RFC_READ_TABLEClient : System.ServiceModel.ClientBase<RFCReadTable.ZWS_RFC_READ_TABLE>, RFCReadTable.ZWS_RFC_READ_TABLE
    {
        
        public ZWS_RFC_READ_TABLEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RFCReadTable.RfcReadTableResponse1 RFCReadTable.ZWS_RFC_READ_TABLE.RfcReadTable(RFCReadTable.RfcReadTableRequest request)
        {
            return base.Channel.RfcReadTable(request);
        }
        
        public RFCReadTable.RfcReadTableResponse RfcReadTable(RFCReadTable.RfcReadTable RfcReadTable1)
        {
            RFCReadTable.RfcReadTableRequest inValue = new RFCReadTable.RfcReadTableRequest();
            inValue.RfcReadTable = RfcReadTable1;
            RFCReadTable.RfcReadTableResponse1 retVal = ((RFCReadTable.ZWS_RFC_READ_TABLE)(this)).RfcReadTable(inValue);
            return retVal.RfcReadTableResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RFCReadTable.RfcReadTableResponse1> RFCReadTable.ZWS_RFC_READ_TABLE.RfcReadTableAsync(RFCReadTable.RfcReadTableRequest request)
        {
            return base.Channel.RfcReadTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<RFCReadTable.RfcReadTableResponse1> RfcReadTableAsync(RFCReadTable.RfcReadTable RfcReadTable)
        {
            RFCReadTable.RfcReadTableRequest inValue = new RFCReadTable.RfcReadTableRequest();
            inValue.RfcReadTable = RfcReadTable;
            return ((RFCReadTable.ZWS_RFC_READ_TABLE)(this)).RfcReadTableAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
